### ISSUE TITLE
Receiving Null Key value exception during ingestion

### ISSUE THREAD

**Issue by parekuti** [tuplejump/FiloDB#102]
WARN  2016-05-26 23:13:05,466 filodb.spark.package$: Exception from flushing nodes for core_fdb.asset_info/0
java.lang.RuntimeException: Unexpected response message: FlushFailed(filodb.core.NullKeyValue: Null partition value for col index 0)
        at filodb.coordinator.client.Client$$anonfun$standardResponse$1.applyOrElse(Client.scala:30) ~[filodb-spark-assembly.jar:0.3]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.5.jar:na]
        at filodb.coordinator.client.IngestionOps$$anonfun$flush$1.applyOrElse(IngestionOps.scala:23) ~[filodb-spark-assembly.jar:0.3]
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162) ~[scala-library-2.10.5.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.10.5.jar:na]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) ~[scala-library-2.10.5.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
        at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.5.jar:na]
        at filodb.coordinator.client.Client$.actorsAsk(Client.scala:37) ~[filodb-spark-assembly.jar:0.3]
        at filodb.coordinator.client.ClusterClient.askAllCoordinators(Client.scala:98) ~[filodb-spark-assembly.jar:0.3]
        at filodb.coordinator.client.IngestionOps$class.flush(IngestionOps.scala:23) ~[filodb-spark-assembly.jar:0.3]
        at filodb.coordinator.client.ClusterClient.flush(Client.scala:80) ~[filodb-spark-assembly.jar:0.3]
        at filodb.coordinator.client.IngestionOps$class.flushCompletely(IngestionOps.scala:59) ~[filodb-spark-assembly.jar:0.3]
        at filodb.coordinator.client.ClusterClient.flushCompletely(Client.scala:80) ~[filodb-spark-assembly.jar:0.3]
        at filodb.spark.FiloContext$.insertIntoFilo$extension(FiloContext.scala:167) [filodb-spark-assembly.jar:0.3]
        at filodb.spark.FiloContext$.saveAsFilo$extension(FiloContext.scala:124) [filodb-spark-assembly.jar:0.3]
        at filodb.spark.DefaultSource.createRelation(DefaultSource.scala:65) [filodb-spark-assembly.jar:0.3]
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:309) [spark-sql_2.10-1.4.2.4.jar:1.4.2.4]
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144) [spark-sql_2.10-1.4.2.4.jar:1.4.2.4]

**Comment by velvia** [comment]
This is likely the same error as #103.  Should we close one of these?

**Comment by parekuti** [comment]
Yes, we can close this issue, as this is related to the write problem that i was facing when dataframe is sorted by full primary key instead of sorted by partition key only.
