### ISSUE TITLE
Getting error from ingestRDDRows method randomly

### ISSUE THREAD

**Issue by parekuti** [tuplejump/FiloDB#103]
org.apache.spark.scheduler.TaskSetManager: Lost task 40.0 in stage 6.0 (TID 604, 10.1.12.17): scala.MatchError: IngestionErr(Ingestion actors shut down, check error logs) (of class filodb.coordinator.RowSource$IngestionErr)
    at filodb.spark.package$.ingestRddRows(package.scala:90)
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:159)
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:155)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:703)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:703)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
    at org.apache.spark.scheduler.Task.run(Task.scala:70)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
WARN  2016-05-16 21:58:07,466 org.apache.spark.scheduler.TaskSetManager: Lost task 40.1 in stage 6.0 (TID 645, 10.1.12.17): akka.actor.InvalidActorNameException: actor name [transaction_fdb.vehicle_order_info2_0_40] is not unique!
    at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130)

**Comment by velvia** [comment]
This should be fixed by PR #102

**Comment by velvia** [comment]
This should be fixed by the PR that just got merged
