### ISSUE TITLE
GDELT data population fails

### ISSUE THREAD

**Issue by ffarozan** [tuplejump/FiloDB#52]
I am trying to follow the steps to try FiloDB. filo-cli init succeeded.

I am stuck in next step. The error looks more Cassandra specific. But any config in spark to fix this problem?

scala> csvDF.write.format("filodb.spark").
     |              option("dataset", "gdelt").
     |              option("sort_column", "GLOBALEVENTID").
     |              mode(SaveMode.Overwrite).save()
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_4_piece0 on localhost:36922 in memory (size: 19.3 KB, free: 534.5 MB)
16/01/03 11:16:14 INFO package$: Truncating dataset gdelt
16/01/03 11:16:14 INFO package$: Creating dataset Dataset(gdelt,List(Projection(0,gdelt,GLOBALEVENTID,false,List(),10000)),_partition,{"chunkSize":1000,"segmentSize":"10000"})...
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_5_piece0 on localhost:36922 in memory (size: 1842.0 B, free: 534.5 MB)
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_6_piece0 on localhost:36922 in memory (size: 19.3 KB, free: 534.5 MB)
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_7_piece0 on localhost:36922 in memory (size: 1834.0 B, free: 534.5 MB)
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_8_piece0 on localhost:36922 in memory (size: 19.3 KB, free: 534.5 MB)
16/01/03 11:16:14 INFO BlockManagerInfo: Removed broadcast_9_piece0 on localhost:36922 in memory (size: 3.7 KB, free: 534.5 MB)
16/01/03 11:16:14 INFO package$: Dataset gdelt created successfully...
16/01/03 11:16:14 INFO package$: Read schema for dataset gdelt = Map(ActionGeo_CountryCode -> Column(ActionGeo_CountryCode,gdelt,0,StringColumn,FiloSerializer,false,false), Actor1Geo_FullName -> Column(Actor1Geo_FullName,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2Name -> Column(Actor2Name,gdelt,0,StringColumn,FiloSerializer,false,false), ActionGeo_ADM1Code -> Column(ActionGeo_ADM1Code,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2CountryCode -> Column(Actor2CountryCode,gdelt,0,StringColumn,FiloSerializer,false,false), Actor1Name -> Column(Actor1Name,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2Religion2Code -> Column(Actor2Religion2Code,gdelt,0,StringColumn,FiloSerializer,false,false), Actor1KnownGroupCode -> Column(Actor1KnownGroupCode,gdelt,0,StringColumn,FiloSerializer,false,false), ActionGeo_Type -> Column(ActionGeo_Type,gdelt,0,IntColumn,FiloSerializer,false,false), Actor1Geo_Type -> Column(Actor1Geo_Type,gdelt,0,IntColumn,FiloSerializer,false,false), Actor1Religion1Code -> Column(Actor1Religion1Code,gdelt,0,StringColumn,FiloSerializer,false,false), EventCode -> Column(EventCode,gdelt,0,IntColumn,FiloSerializer,false,false), Actor1Geo_Long -> Column(Actor1Geo_Long,gdelt,0,DoubleColumn,FiloSerializer,false,false), Actor1EthnicCode -> Column(Actor1EthnicCode,gdelt,0,StringColumn,FiloSerializer,false,false), GLOBALEVENTID -> Column(GLOBALEVENTID,gdelt,0,IntColumn,FiloSerializer,false,false), NumMentions -> Column(NumMentions,gdelt,0,IntColumn,FiloSerializer,false,false), Actor2KnownGroupCode -> Column(Actor2KnownGroupCode,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2Code -> Column(Actor2Code,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2Geo_Lat -> Column(Actor2Geo_Lat,gdelt,0,DoubleColumn,FiloSerializer,false,false), FractionDate -> Column(FractionDate,gdelt,0,DoubleColumn,FiloSerializer,false,false), Actor2Geo_Long -> Column(Actor2Geo_Long,gdelt,0,DoubleColumn,FiloSerializer,false,false), Actor1Code -> Column(Actor1Code,gdelt,0,StringColumn,FiloSerializer,false,false), Actor1Type2Code -> Column(Actor1Type2Code,gdelt,0,StringColumn,FiloSerializer,false,false), Actor2Geo_FullName -> Column(Actor2Geo_FullName,gdelt,0,StringColumn,FiloSerializer,false,false))
16/01/03 11:16:14 INFO package$: Matching columns - Set(ActionGeo_CountryCode, Actor1Geo_FullName, Actor2Name, ActionGeo_ADM1Code, Actor2CountryCode, Actor1Name, Actor2Religion2Code, Actor1KnownGroupCode, ActionGeo_Type, Actor1Geo_Type, Actor1Religion1Code, EventCode, Actor1Geo_Long, Actor1EthnicCode, GLOBALEVENTID, NumMentions, Actor2KnownGroupCode, Actor2Code, Actor2Geo_Lat, FractionDate, Actor2Geo_Long, Actor1Code, Actor1Type2Code, Actor2Geo_FullName)
Missing columns - Set(DATEADDED, Actor2Geo_Type, IsRootEvent, Actor2EthnicCode, Actor2Type2Code, Actor2Type1Code, NumSources, AvgTone, Actor1Type3Code, Actor1Geo_Lat, NumArticles, ActionGeo_FullName, Year, Actor1Geo_FeatureID, ActionGeo_Long, Actor2Geo_ADM1Code, GoldsteinScale, Actor2Geo_CountryCode, Actor1Geo_ADM1Code, Actor1Religion2Code, EventBaseCode, MonthYear, ActionGeo_Lat, ActionGeo_FeatureID, Actor2Religion1Code, QuadClass, Actor1Type1Code, Actor2Type3Code, Actor1Geo_CountryCode, EventRootCode, _partition, SQLDATE, Actor1CountryCode, Actor2Geo_FeatureID)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
16/01/03 11:16:16 ERROR phantom: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
filodb.core.StorageEngineException: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
	at filodb.cassandra.Util$ResultSetToResponse$$anonfun$toResponse$1.applyOrElse(Util.scala:19)
	at filodb.cassandra.Util$ResultSetToResponse$$anonfun$toResponse$1.applyOrElse(Util.scala:18)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Failure.recover(Try.scala:185)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
	at com.datastax.driver.core.exceptions.WriteTimeoutException.copy(WriteTimeoutException.java:59)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:117)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:120)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186)
	at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:45)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:754)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:590)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:994)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:916)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	... 1 more
Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:62)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:40)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:243)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:225)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 11 more

**Comment by velvia** [comment]
Hi Firdousi, 

Thanks for trying!  First, if you go into cqlsh, do you see a keyspace “filodb” and what tables are there?

You can configure spark-shell when you start up with some parameters:

-Dfilodb.cassandra.host=127.0.0.1
-Dfilodb.cassandra.port=9042
-Dfilodb.cassandra.keyspace=filodb

My guess is that it is something to do with “localhost”, which is the default host name, somehow not working for you?

-Evan

**Comment by ffarozan** [comment]
I am using ccm. After the filo-cli init, I could see the filodb keyspace and two tables. 

And after executing the commands in spark shell, I see two more tables related to GDELT also created. But somehow the data population only fails.

ffarozan@ffarozan-2-VirtualBox:~/FiloDB$ netstat -an | grep 9042
tcp        0      0 127.0.0.2:9042          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:9042          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:43034         127.0.0.1:9042          TIME_WAIT  
tcp        0      0 127.0.0.1:43033         127.0.0.1:9042          TIME_WAIT  
ffarozan@ffarozan-2-VirtualBox:~/FiloDB$ ccm status
Cluster: 'test210'
------------------
node1: UP
node2: UP
ffarozan@ffarozan-2-VirtualBox:~/FiloDB$ ccm node1 cqlsh
Connected to test210 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.0 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> use filodb;
cqlsh:filodb> desc tables;

gdelt_chunkmap  datasets  gdelt_chunks  columns

cqlsh:filodb>

**Comment by ffarozan** [comment]
It succeeded this time, without any change. For a different reason, I had to restart the VM and it is working fine. Data population is done. Let me try the queries.

**Comment by velvia** [comment]
Awesome, glad to hear.  Perhaps just needed increased cassandra timeouts.  Will need to add that as a config option.

**Comment by ffarozan** [comment]
Thanks

**Comment by velvia** [comment]
@ffarozan so how did the queries go?

**Comment by ffarozan** [comment]
@velvia it worked fine. I tested with a limited subset of gdelt.
