### ISSUE TITLE
Unable to recreate table using CLI when data is present

### ISSUE THREAD

**Issue by parekuti** [tuplejump/FiloDB#73]
Drop table option is not available right now.  Also getting an exception when trying to recreate table if there is data in it. Recreate table works when there is no data in that table.
```./filo-cli-0.2-SNAPSHOT -Dconfig.file=./filodb-element.conf --command create --dataset billing_fact_native2 --columns  ge_fiscal_period_name:string,corp_code:string,fleet_number:string,consolidated_billing_source_cd:string,security_level:string,charge_type_desc:string,charge_cd:string,asset_id:string,billing_invoice_id:string,billing_invoice_line_num:string,asset_class_cd:string,asset_make_desc:string,asset_start_dt:string,bill_level2_id_desc:string,bill_level3_id_desc:string,bill_level4_id_desc:string,bill_level5_id_desc:string,bill_level6_id_desc:string,billing_period_id:string,billing_structure_party_id:string,billing_structure_start_dt:string,charge_desc:string,cust_inv_odom_reading_qty:string,fuel_negotiated_discount_amt:string,fuel_product_type_desc:string,fuel_trans_category_desc:string,fuel_trans_loctn_city_name:string,fuel_trans_time:string,ge_fiscal_quarter_name:string,ge_fiscal_year_name:string,ge_unit_num:string,inventory_status_desc:string,license_plate_state_cd:string,line_item_qty:string,model_desc:string,mso_first_name:string,mso_last_name:string,purchase_transaction_dt:string,svcs_net_amt:string,vntg_year:string --partitionKeys corp_code,fleet_number,ge_fiscal_period_name --rowKeys consolidated_billing_source_cd,securitylevel,charge_type_desc,charge_cd,asset_id,billing_invoice_id,billing_invoice_line_num --segmentKey ':string /0'
Creating dataset billing_fact_native2...
Uncaught exception:
java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
at scala.concurrent.Await$.result(package.scala:107)
at filodb.cli.CsvImportExport$class.parse(CsvImportExport.scala:43)
at filodb.cli.CliMain$.parse(CliMain.scala:57)
at filodb.cli.CsvImportExport$class.actorAsk(CsvImportExport.scala:49)
at filodb.cli.CliMain$.actorAsk(CliMain.scala:57)
at filodb.cli.CliMain$.createDatasetAndColumns(CliMain.scala:157)
at filodb.cli.CliMain$.main(CliMain.scala:88)
at filodb.cli.CliMain$.main(CliMain.scala:57)
at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
at filodb.cli.CliMain$.main(CliMain.scala:57)
at filodb.cli.CliMain.main(CliMain.scala)```

**Comment by velvia** [comment]
There is a drop table option - `--command delete`.  However, the error above could be clearer when the table already exists.
