### ISSUE TITLE
Can't initialize with Cassandra 3.4

### ISSUE THREAD

**Issue by divanikus** [tuplejump/FiloDB#93]
I already had running Cassandra 3.4 instance, so I wished to try FiloDB with it. Unfortunatelly all I got was this:
```
Initializing FiloDB Cassandra tables...
Uncaught exception:
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.TransportException: [localhost/0:0:0:0:0:0:0:1:9042] Cannot connect)
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:229)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:84)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1269)
        at com.datastax.driver.core.Cluster.init(Cluster.java:158)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:248)
        at com.websudos.phantom.connectors.DefaultSessionProvider.createSession(DefaultSessionProvider.scala:52)
        at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
        at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
        at com.websudos.phantom.connectors.Cache$Lazy.get$lzycompute(DefaultSessionProvider.scala:77)
        at com.websudos.phantom.connectors.Cache$Lazy.get(DefaultSessionProvider.scala:77)
        at com.websudos.phantom.connectors.Cache.getOrElseUpdate(DefaultSessionProvider.scala:96)
        at com.websudos.phantom.connectors.DefaultSessionProvider.getSession(DefaultSessionProvider.scala:57)
        at com.websudos.phantom.connectors.KeySpaceDef.session$lzycompute(Keyspace.scala:66)
        at com.websudos.phantom.connectors.KeySpaceDef.session(Keyspace.scala:66)
        at filodb.cassandra.FiloCassandraConnector$class.session(FiloCassandraConnector.scala:48)
        at filodb.cassandra.metastore.ColumnTable.session$lzycompute(ColumnTable.scala:18)
        at filodb.cassandra.metastore.ColumnTable.session(ColumnTable.scala:18)
        at filodb.cassandra.FiloCassandraConnector$class.createKeyspace(FiloCassandraConnector.scala:58)
        at filodb.cassandra.metastore.ColumnTable.createKeyspace(ColumnTable.scala:18)
        at filodb.cassandra.metastore.CassandraMetaStore.initialize(CassandraMetaStore.scala:21)
        at filodb.cli.CliMain$$anonfun$main$3.apply(CliMain.scala:87)
        at filodb.cli.CliMain$$anonfun$main$3.apply(CliMain.scala:87)
        at filodb.cli.CsvImportExport$class.parseResponse(CsvImportExport.scala:32)
        at filodb.cli.CliMain$.parseResponse(CliMain.scala:59)
        at filodb.cli.CsvImportExport$class.awaitSuccess(CsvImportExport.scala:42)
        at filodb.cli.CliMain$.awaitSuccess(CliMain.scala:59)
        at filodb.cli.CliMain$.main(CliMain.scala:87)
        at filodb.cli.CliMain$.main(CliMain.scala:59)
        at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
        at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
        at filodb.cli.CliMain$.main(CliMain.scala:59)
        at filodb.cli.CliMain.main(CliMain.scala)
```

**Comment by velvia** [comment]
@divanikus thanks, haven't had a chance to test with C* 3.x yet.  Most likely will require moving to a newer version of the C* driver.

**Comment by velvia** [comment]
@divanikus feel free to try again.  Just merged in a change that upgrades to C* Java Driver 3.0.x, so this should work for talking to 3.x clusters.
